[metadata]
categories = ["googleCloud"]
description = "map me cloudrunjob admin provider for wasmcloud components"
license = "MIT"
repository = "https://github.com/Mattilsynet/map-me-gcp-cloudrunjob"
