// Generated by `wit-bindgen-wrpc-go` 0.11.0. DO NOT EDIT!
// provider package contains wRPC bindings for `provider` world
package provider

import (
	exports__mattilsynet__me_gcp_cloudrun_job_admin__me_gcp_cloudrun_job_admin "github.com/Mattilsynet/map-me-gcp-cloudrunjob/bindings/exports/mattilsynet/me_gcp_cloudrun_job_admin/me_gcp_cloudrun_job_admin"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__mattilsynet__me_gcp_cloudrun_job_admin__me_gcp_cloudrun_job_admin.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__mattilsynet__me_gcp_cloudrun_job_admin__me_gcp_cloudrun_job_admin.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
